stages:
  - binary_build
  - deploy

variables:
  DATADOG_AGENT_WINBUILDIMAGES: v4319944-68f7e12

.manual:
  - when: manual
    allow_failure: true

.build_common:
  stage: binary_build
  tags: ["runner:windows-docker", "windowsversion:1809"]
  variables:
    ARCH: "x64"
  script:
    - $ErrorActionPreference = "Stop"
    - '$_instance_id = (iwr  -UseBasicParsing http://169.254.169.254/latest/meta-data/instance-id).content ; Write-Host "Running on instance $($_instance_id)"'
    - if (Test-Path build-out) { remove-item -recurse -force build-out }
    - docker run --rm -v "$(Get-Location):c:\mnt" -e CI_JOB_ID=${CI_JOB_ID} -e WINDOWS_BUILDER=true -e AWS_NETWORKING=true -e TARGET_ARCH="$ARCH" 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/windows_1809_${ARCH}:${Env:DATADOG_AGENT_WINBUILDIMAGES} C:\mnt\build.bat
    - get-childitem build-out
    - Get-FileHash -Algorithm SHA256 build-out/python-windows-2.7.18-${ARCH}.zip
  artifacts:
    expire_in: 2 weeks
    paths:
      - build-out/python-windows-2.7.18-${ARCH}.zip

build_binaries_x64:
  extends: .build_common
  variables:
    ARCH: "x64"

build_binaries_x86:
  extends: .build_common
  variables:
    ARCH: "x86"

deploy_x64:
  stage: deploy
  tags: ["runner:windows-docker", "windowsversion:1809"]
  needs: ["build_binaries_x64"]
  rules:
    !reference [.manual]
  script:
    - Invoke-Expression "aws s3 cp --only-show-errors --region us-east-1 --sse AES256 --acl public-read build-out/python-windows-2.7.18-x64.zip s3://dd-agent-omnibus/test-python-windows-2.7.18-x64.zip"

deploy_x86:
  stage: deploy
  tags: ["runner:windows-docker", "windowsversion:1809"]
  needs: ["build_binaries_x86"]
  rules:
    !reference [.manual]
  script:
    - Invoke-Expression "aws s3 cp --only-show-errors --region us-east-1 --sse AES256 --acl public-read build-out/python-windows-2.7.18-x86.zip s3://dd-agent-omnibus/test-python-windows-2.7.18-x86.zip"